import { readFileSync, mkdirSync, writeFileSync } from "node:fs";
import { foldVariants, hasVariants } from "./shared/variants.js";
import type { NameKind, PackedEntry, PackedLexicon } from "./shared/types.js";

const INPUT_PATH = "internal/.cache/unidic.tsv";
const OUTPUT_DIR = "src/data/generated";
const LEXICON_PATH = `${OUTPUT_DIR}/unidic.ts`;
const META_PATH = `${OUTPUT_DIR}/meta.ts`;

interface RawEntry {
  kind: NameKind;
  surface: string;
  reading: string;
  normalized: string;
  sourceFlags: number;
}

function loadTsv(): RawEntry[] {
  const content = readFileSync(INPUT_PATH, "utf-8");
  const lines = content.trim().split("\n");
  // Skip header
  return lines.slice(1).map((line) => {
    const [kind, surface, reading, normalized, _source, _sourceId, sourceFlags] =
      line.split("\t");
    return {
      kind: kind as NameKind,
      surface,
      reading,
      normalized,
      sourceFlags: parseInt(sourceFlags, 10),
    };
  });
}

function buildLexicon(entries: RawEntry[]): PackedLexicon {
  const sei: Record<string, PackedEntry> = {};
  const mei: Record<string, PackedEntry> = {};
  const readingSei: Record<string, number> = {};
  const readingMei: Record<string, number> = {};
  const folded: Record<string, string[]> = {};
  let maxSeiLen = 0;
  let maxMeiLen = 0;

  // Aggregate by kind + surface (keep first reading, OR flags)
  const aggregated = new Map<string, RawEntry>();
  for (const entry of entries) {
    const key = `${entry.kind}\t${entry.surface}`;
    const existing = aggregated.get(key);
    if (existing) {
      existing.sourceFlags |= entry.sourceFlags;
    } else {
      aggregated.set(key, { ...entry });
    }
  }

  for (const entry of aggregated.values()) {
    const packed: PackedEntry = [
      entry.sourceFlags,
      entry.reading,
      entry.normalized,
    ];

    if (entry.kind === "sei") {
      sei[entry.surface] = packed;
      maxSeiLen = Math.max(maxSeiLen, [...entry.surface].length);
      if (entry.reading) {
        readingSei[entry.reading] = (readingSei[entry.reading] ?? 0) | entry.sourceFlags;
      }
    } else {
      mei[entry.surface] = packed;
      maxMeiLen = Math.max(maxMeiLen, [...entry.surface].length);
      if (entry.reading) {
        readingMei[entry.reading] = (readingMei[entry.reading] ?? 0) | entry.sourceFlags;
      }
    }

    // Build folded index for variant kanji
    if (hasVariants(entry.surface)) {
      const foldedKey = foldVariants(entry.surface);
      if (!folded[foldedKey]) {
        folded[foldedKey] = [];
      }
      if (!folded[foldedKey].includes(entry.surface)) {
        folded[foldedKey].push(entry.surface);
      }
    }
  }

  return {
    sei,
    mei,
    reading: { sei: readingSei, mei: readingMei },
    folded,
    maxSeiLen,
    maxMeiLen,
  };
}

function writeLexiconModule(lexicon: PackedLexicon): void {
  mkdirSync(OUTPUT_DIR, { recursive: true });

  const json = JSON.stringify(lexicon);
  const code = `// Auto-generated by tools/build/pack.ts — do not edit

export type PackedEntry = readonly [
  flags: number,
  reading: string,
  normalized: string,
];

export interface PackedLexicon {
  sei: Record<string, PackedEntry>;
  mei: Record<string, PackedEntry>;
  reading: {
    sei: Record<string, number>;
    mei: Record<string, number>;
  };
  folded: Record<string, string[]>;
  maxSeiLen: number;
  maxMeiLen: number;
}

export const lexicon: PackedLexicon = ${json} as const;
`;
  writeFileSync(LEXICON_PATH, code, "utf-8");

  const seiCount = Object.keys(lexicon.sei).length;
  const meiCount = Object.keys(lexicon.mei).length;
  const foldedCount = Object.keys(lexicon.folded).length;

  console.log(
    `Packed lexicon: sei=${seiCount}, mei=${meiCount}, folded=${foldedCount}, maxSeiLen=${lexicon.maxSeiLen}, maxMeiLen=${lexicon.maxMeiLen}`
  );
  console.log(`Written to ${LEXICON_PATH}`);
}

function writeMetaModule(): void {
  const code = `// Auto-generated by tools/build/pack.ts — do not edit
export const meta = {
  source: "UniDic (現代書き言葉UniDic)",
  version: "202512",
  license: "BSD-3-Clause (selected from GPL-2.0 / LGPL-2.1 / BSD-3-Clause triple license)",
  url: "https://clrd.ninjal.ac.jp/unidic/",
  extractedAt: "${new Date().toISOString().split("T")[0]}",
} as const;
`;
  writeFileSync(META_PATH, code, "utf-8");
  console.log(`Written to ${META_PATH}`);
}

function main(): void {
  const entries = loadTsv();
  const lexicon = buildLexicon(entries);
  writeLexiconModule(lexicon);
  writeMetaModule();
}

main();
